import Head from 'next/head'
import { Inter } from '@next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import React, { useRef } from "react";
import Container from 'react-bootstrap/Container';
import Nav from 'react-bootstrap/Nav';
import Navbar from 'react-bootstrap/Navbar';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const nameRef = useRef(null);
  const addressRef = useRef(null);
  const messageRef = useRef(null);

  const handleSubmit = async (e) => {
    e.preventDefault();

    let name = nameRef.current?.value;
    if (name == "") {
      name = "名無し";
    }

    let data = {
      name: name,
      address: addressRef.current?.value,
      message: messageRef.current?.value,
    }

    await fetch("api/contact", {
      method: "POST",
      headers: {
        "Content-type": "application/json",
      },
      body: JSON.stringify(data),
    }).then((res) => {
      if (res.status === 200) {
        messageRef.current.value = "送信しました。";
        console.log("メール送信成功");
      };
    });
  };

  return (
    <>
      <Head>
        <title>お悩み相談フォーム</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar className="center">
          <Container>
              <Navbar.Brand href="../">←Home</Navbar.Brand>
              <Nav className="ms-auto">
                  <Nav.Link href="https://twitter.com/556soudansitu" target="_blank">Twitter</Nav.Link>
              </Nav>
          </Container>
      </Navbar>

      <div className="container mt-5 all">
        <h2 className="mb-5 text-center">何でもお悩み相談室</h2>
        <div className="mb-5">
          <p>本サイトにお越しいただきありがとうございます。</p>
          <p>
            この相談室ではどのようなジャンルの相談に対しても丁寧な対応でご返信することを心がけています。
            <br />
            モヤモヤしているけれど近しい人にはできない相談から個人的な悩み、愚痴などでも構わないのでぜひ相談してみてください。
          </p>
          <p>
            私はカウンセラーや噺家などのプロではないため、解決もできなければ気の利いたことも言えないことがほとんどだと思います、
            <br />
            しかし悩みや自分自身の考え、気持ち等は他人に打ち明けるだけでも心が楽になることがあると思います。
            <br />
            日頃の鬱憤や愚痴などでも構いませんので、ご自身の心をより良く保つためのはけ口として相談してみてはいかがでしょうか？
          </p>
        </div>
        <form onSubmit={(e) => handleSubmit(e)}>
          <div className="mb-3">
            <label htmlFor="name" className="form-label">ニックネーム (入力しなくても構いません)</label>
            <input type="text" className="form-control" id="name" ref={nameRef} />
          </div>
          <div className="mb-3">
            <label htmlFor="name" className="form-label">メールアドレス or TwitterID (返答をご希望の方のみ入力)</label>
            <input type="text" className="form-control" id="name" ref={addressRef} />
          </div>
          <div className="mb-3">
            <label htmlFor="message" className="form-label">内容 (送信完了時に内容が「送信しました。」と変更されます)</label>
            <textarea name="message" id="message" className="form-control cc" ref={messageRef} required></textarea>
          </div>
          <button type="submit" className="btn btn-danger mb-5">送信</button>
        </form>
      </div>
    </>
  )
}
